/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_mst_nsh9b3_privacypreservingfaceauthentication_AuthenticateFace */

#ifndef _Included_edu_mst_nsh9b3_privacypreservingfaceauthentication_AuthenticateFace
#define _Included_edu_mst_nsh9b3_privacypreservingfaceauthentication_AuthenticateFace
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_mst_nsh9b3_privacypreservingfaceauthentication_AuthenticateFace
 * Method:    nativeCreateLBPHistorgram
 * Signature: (JJII)J
 */
JNIEXPORT void JNICALL Java_edu_mst_nsh9b3_privacypreservingfaceauthentication_AuthenticateFace_nativeCreateLBPHistorgram
  (JNIEnv *, jclass, jlong, jlong, jint, jint);

/*
 * Class:     edu_mst_nsh9b3_privacypreservingfaceauthentication_AuthenticateFace
 * Method:    nativeSpatialHistogram
 * Signature: (JJII)J
 */
JNIEXPORT void JNICALL Java_edu_mst_nsh9b3_privacypreservingfaceauthentication_AuthenticateFace_nativeSpatialHistogram
(JNIEnv *, jclass, jlong, jlong, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
